project_urls:
  Bug Tracker: https://github.com/AllenCell/napari-allencell-segmenter/issues
  Documentation: https://github.com/AllenCell/napari-allencell-segmenter#README.md
  Source Code: https://github.com/AllenCell/napari-allencell-segmenter
  User Support: https://github.com/AllenCell/napari-allencell-segmenter/issues