# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - 3D image
  - Cell segmentation
  - Model-based segmentation
  - Fluorescence microscopy
  - Image visualisation
